Hugal31/yara-rust

Cargo.toml, src/compiler.rs, src/errors.rs, src/internals/rules.rs, src/rules.rs
Use _thiserror_ instead of _failure_. I chose _thiserror_ because:
* It behaves closely to _failure_.
* It reached the 1.0 version.
* It is popular (3,342,266 download on crates.io as I right this lines).
Con: thiserror do not have a `context` mechanism, so there is some little boilerplate with IoError.
Closes #9
=> refactor: use thiserror instead of the failure crate

.travis.yml, Cargo.toml, yara-sys/Cargo.toml, yara-sys/README.md, yara-sys/build.rs
Added support for building and linking vendored libyara (useful when you want to statically link libyara).
I tested the crate's tests (with `vendored` feature) on Windows 10, macOS, and Ubuntu.
lmk if there's anything else you want me to change or test
=> Vendored libyara

src/initialize.rs, src/rules.rs
Right now, the Rules struct is Sync but not Send. It's both weird (I don't know any struct in the std or anywhere which is Sync but not Send), and makes it quite hard to use in multi threaded context: you can't pass its ownership to another thread, you can't hold it across `.await` points in tokio, and you can't even put it in a global Mutex. 
I reviewed the libyara from version 3.7 to 4.1-rc1, and it seems to me that it can safely be Send. 
libyara does uses Thread Local Storage variables in its scan_XXX functions, but because
we control the callback, we can ensure thread-safety and the Rules can safely be Send (see the comment).
This PR implements Send, and document the rationale behind it.
The only pain-point was `finalize_thread`. It is admittedly [a bad …
=> make Rules impl Send

Cargo.toml, README.md, src/compiler.rs, src/internals/rules.rs, src/internals/scan.rs, src/lib.rs, src/rules.rs, src/scanner.rs, yara-sys/build.rs
This PR adds support for creating scanners from a set of Rules, defining external variables for them, and performing scans with them.
There was one major issue: scanners API was added in v3.8.0, and therefore is missing in v3.7.0. This means that compilation of this crate from 3.7 headers files would break due to missing functions.
For now I've put everything related to scanners behind `#[cfg(feature = "scanners")]`, but this is not ideal. From here you might consider:
* Dropping v3.7.0 support, since this release is a pain to handle, and you've seem to have had a hard time to support it in other modules as well. This might be in line with what you have already planned for v4.x support.
* Accept this PR as is, and add documentation for the `scanners` feature, and how it is incompatible …
=> Add scanners

.gitmodules, yara-sys/Cargo.toml, yara-sys/build.rs
The crate is no longer maintained, has bugs, compiles the wrong proc.c, and
is simple and small enough for us to have it entirely in our build.rs
The "vendored" feature now directly compiles libyara v3.11.0 from the added
submodule with cc.
Right now this is still v3.11.0, but when you'll want to update to v4, you'll just have to update the submodule. 
Should unblock #18 and #13
=> refactor: remove dependency on yara-src-rs

README.md, src/internals/scan.rs, src/rules.rs, src/scanner.rs
This PR adds bindings for `yr_rules_scan_proc` and `yr_scanner_scan_proc`. 
Note that for some reason, these functions are not documented on [the C api doc](https://yara.readthedocs.io/en/stable/capi.html) of libyara, but they do work properly.
I added unit tests for both functions, which create dummy shell processes and scan their memory in search of a magic string. They work on both linux and windows.
When using feature "vendored", there is a bug in yara-src-rs where [the wrong file is compiled](https://github.com/yoavk/yara-src-rs/issues/2), which is blocking this PR. A [PR](https://github.com/yoavk/yara-src-rs/pull/1) to yara-src-rs which fixes this issue is already opened since 19 days, but the maintainer doesn't seem to be active. 
You can verify the yara-src-rs PR actually solves …
=> Draft: feat: scan process memory

.travis.yml, Cargo.toml, yara-sys/Cargo.toml, yara-sys/README.md, yara-sys/bindings/yara-4.1.0-unix.rs, yara-sys/bindings/yara-4.1.0-windows.rs, yara-sys/build.rs, yara-sys/src/errors/mod.rs
Version 4.1.0 of libyara was just released, add support for it.
This replaces the bundled bindings for v4.0.2 with bundled bindings for v4.1.0. 
I've added the version patch number in the name of the `bundled-4_1_0` feature, because yara does not use semantic versioning, and patch updates sometimes still break compatibility, so I wanted to make it extra clear which one it is based on.
=> feat: support v4.1.0

src/internals/stream.rs
To be able to compile to 32bit platforms such as `wasm32-unknown-emscripten`, `size_t` needs to be used instead of `u64` due to the fact that it's 32bit and resolves to `u32` in such cases.
=> Add 32bit support

yara-sys/build.rs
I've just lost a week debugging an optimized [undefined behaviour in libyara](https://github.com/VirusTotal/yara/issues/1302) which was clearly hinted by clang, but the warnings were suppressed in the build.rs.
This PR re-enables all warnings, except for a few harmless warning families to avoid spam during compilation. 
I've tried to review all the warnings we get on x86, x64, linux, windows, with both clang and cl, and disable all warning families that are clearly harmless for us. The only one that concerns me is `-Wsign-compare`, but it also is the more frequent by far, so I've also disabled it.
=> show cc compilation wanings

src/internals/scan.rs, src/rules.rs, src/scanner.rs, tests/tests.rs
Hello @Hugal31 , sorry for my english, I will try to describe what I want to do.
1. I kept the old api for backward compatibility
2. Callback api provides more control over scanning
3. I am writing an engine that will be integrated with python. To avoid converting from a Vec<Rule> to PyList, I want to immediately add Rule to PyList
If this PR is Ok, I can write Callback API for Scanner
=> Add callback API into Rules

src/compiler.rs, src/internals/compiler.rs, src/internals/scan.rs, src/rules.rs, src/scanner.rs, tests/tests.rs
Add API for work with open file:
Rules, Scanner: scan_fd, scan_fd_callback
Compiler: add_rules_fd, add_rules_fd_with_namespace
It is very useful when creating a temporary file.
=> Work with open file in Rules, Scanner and Compiler

.github/workflows/release.yaml
Create simple workflow for release crate. 
Flow:
1. checkout with submodule
2. publish to https://crates.io/
3. create release in Github
@Hugal31 what do you think it would be useful and help to avoid future problems: https://github.com/Hugal31/yara-rust/issues/48?
=> feature: add github workflow for release

src/internals/matches.rs
Strings in yara rules can be declared as "private": this means those strings won't be reported in the results.
How this is implemented is however pretty surprising. Such strings are still included in the YR_RULE object, and their matches are returned as well, but with a `is_private` flag set to true. Yes, the flag is on the matches, and not even on the string...
Those matches are then filtered by the helper `yr_string_matches_foreach`, and this filtering was missing in the rust version.
=> fix: do not list private matches in scan results

src/internals/iterator.rs, tests/tests.rs
@Hugal31 hello! Rust slice know his size. I change constructor for `MemoryBlock`. Now `size` get from slice instead of explicitly passing it as a parameter.
=> feat: change MemoryBlock constructor

src/internals/compiler.rs, src/internals/rules.rs, tests/tests.rs
The namespace was freed before the pointer to it was provided to the yara API.
This leads to an invalid read, which in my tests did not crash, but ended up with a namespace named "" instead of the provided name.
the add_rules_str_with_namespace API does not have the issue, the namespace already has a `as_ref()` call.
I added a regression test as well.
=> fix use after free in add_rules_file_with_namespace

src/internals/iterator.rs
The current release do not build on x86 since 4bb31911036722b03a2e0239b564b4b813fb5180
This is because a field of a sys struct is being filled with a value of type u64. This field is declared as size_t in C, which is bindgen'd into either a u64 on x86_64 (thus it compiles), or a u32 on i686 (thus the compilation error).
Fix this by letting the compiler pick the right cast.
Would be nice to have a build on x86 in the github workflows to catch those!
=> fix compilation of 0.16 release on i686

src/errors.rs, src/rules.rs, src/scanner.rs, tests/tests.rs, yara-sys/build.rs
Fix the new warnings that are making the github actions fail:
- Move the arguments in the format string where possible
- Remove one useless lifetime in a test function
=> Fix 1.67 clippy warnings

src/internals/matches.rs, src/matches.rs
This is needed to calculate the offset of a match when using iterators over blocks.
See `base` at  https://yara.readthedocs.io/en/v4.2.3/capi.html?highlight=YR_RULES#c.YR_MATCH
=> fix: add base offset for scanning memory chunks

yara-sys/build.rs
If OpenSSL's headers are not installed in a standard path, compiling yara in vendored mode with YARA_CRYPTO_LIB=openssl is not possible, as there is no way to provide the include path for OpenSSL (only OPENSSL_LIB_DIR is available, but no OPENSSL_INCLUDE_DIR).
Fix this by:
- Handling OPENSSL_DIR, from which the include and lib dirs are extrapolated.
- Otherwise, handle OPENSSL_LIB_DIR (already done) and OPENSSL_INCLUDE_DIR (addition from this MR).
This is done so that the behavior aligns with the rust bindings for openssl: https://docs.rs/openssl/latest/openssl/#manual
This way, if a crate uses both the openssl and the yara crate, setting those env variables will work for both.
=> feat: add include path to openssl in vendored mode

yara-sys/src/errors/mod.rs
Handle the ERROR_COULD_NOT_READ_PROCESS_MEMORY error from YARA. This error can happen quite often when using the `scan_process` method, so mapping it is a nice QoL, instead of having to match on `Error::Unknown(47)`.
=> feat: add CouldNotReadProcessMemory error

yara-sys/build.rs
YARA depends on having WORDS_BIGENDIAN defined on big endian archs to properly handle this endianness. This is done in the configure of YARA, but is missing in the build script here.
=> fix: properly compile YARA on big-endian arch

Cargo.toml, yara-sys/Cargo.toml, yara-sys/README.md, yara-sys/build.rs
1. Added `YARA_OPENSSL_STATIC` env for static linking with `openssl`
2. Rename env `OPENSSL_DIR` to `YARA_OPENSSL_DIR` - remove name conflict with `rust-openssl`
3. Rename env `OPENSSL_LIB_DIR` to `YARA_OPENSSL_LIB_DIR` - remove name conflict with `rust-openssl`
4. Rename env `OPENSSL_INCLUDE_DIR` to `YARA_OPENSSL_INCLUDE_DIR` - remove name conflict with `rust-openssl`
5. Rename env `LIBYARA_STATIC` to `YARA_STATIC` - for uniform with other envs
6. Improve doc
@vthib you added envs for `openssl`, can you look at the PR? My thought was: remove name conflict with `rust-openssl`, maybe I am not right and it's ok.
=> feat: Add option to static linking with openssl

yara-sys/build.rs
When targeting `x86_64-unknown-linux-musl`, the default features will successfully compile a binary that always segfaults when run (see #106). This is because the default features will try to dynamic link against libyara.so, which means adding it to the list of dynamic dependencies in the resulting ELF for it to be loaded by the `ld` (glibc) interpreter at the start of the program execution. 
However, musl binaries produced by rustc do not have any interpreter, they jump straight to the ELF's entrypoint, and libyara.so is never loaded, even though it is listed as a dynamic dependencies in the ELF.  This of course ultimately results in a segfault when trying to access any memory belonging to libyara.so, since it was not loaded in our address space. 
In my opinion this is a bug in rustc, it …
=> fix: prevent dynamic linking when targeting musl

yara-sys/build.rs
The `vendored` feature will try to compile libyara from sources present in the `yara-sys/yara` folder. When cloning the repo, by default this folder is empty, unless you cloned it with `git clone --recursive`, because git does not initialize submodules unless you ask it to. 
This results in obscure compilation errors about missing `libyara/proc/linux.c`, and can cause quite some confusion for new users that just want to try out the crate (see https://github.com/Hugal31/yara-rust/issues/106#issuecomment-1480920536).
This error only happens when manually cloning the yara-rust repo, and trying it out. When depending on it, cargo will always make sure to recursively clone it.
This PR adds a new check in yara-sys/build.rs to detect an empty `yara-sys/yara` folder, and ask the user to …
=> fix: explicit error when submodule was not cloned

.github/workflows/release.yaml, .github/workflows/tests.yml, Cargo.toml, yara-sys/Cargo.toml, yara-sys/README.md, yara-sys/bindings/yara-4.3.0-x86_64-apple-darwin.rs, yara-sys/bindings/yara-4.3.0-x86_64-pc-windows-gnu.rs, yara-sys/bindings/yara-4.3.0-x86_64-pc-windows-msvc.rs, yara-sys/bindings/yara-4.3.0-x86_64-unknown-linux-gnu.rs, yara-sys/bindings/yara-4.3.0-x86_64-unknown-linux-musl.rs, yara-sys/build.rs
Yara 4.3.0 just got released: https://github.com/VirusTotal/yara/releases/tag/v4.3.0
- Set some new defines needed for the imphash feature in elf module: BUCKETS_128 and CHECKSUM_1B
- Exclude authenticode-parser C files from the PE module if openssl is disabled
- Update generated bindings
- Update feature from `bundled_4_2_3` to `bundled_4_3_0`.
=> Update to Yara 4.3.0

.github/workflows/tests.yml
Replace `actions-rs` to `dtolnay/rust-toolchain` because `actions-rs` is deprecated
=> feat: Replaced deprecated actions-rs to dtolnay/rust-toolchain

yara-sys/README.md
Fix a typo in the `yara-sys` crate's `README.md`
=> Fix typo in `yara-sys` README

yara-sys/Cargo.toml, yara-sys/build.rs
Remove some dependencies of `yara-sys` which are not useful and makes the dependency tree more complex than it should be.
- replace `globwalk` with `glob`: this removes a lot of dependencies, as globwalk used a lot of dependencies that were useless. It removes: bstr, fnv, globset, ignore, same-file, thread_local, walkdir and winapi-util. Some of those took time to update, one still having a bitflags v1 dependency for example.
- remove some unused features of bindgen: logging was unused, and which-rustfmt is also useless: the generated bindings are still formatted, so we do not need it. This removes: log, which, either and once_cell.
=> Slim down dependencies of yara-sys

src/errors.rs
@Hugal31 hello! Library has in public interface type from `yara_sys` crate. I added re-use `yara_sys::Error`.
=> feat: Exposed yara_sys::Error

yara-sys/build.rs
Add support of static linking with OpenSSL on Windows.
Also add a note about a CMake trick (in FindOpenSSL.cmake) that is not supported in Rust.
=> Add support of static linking with OpenSSL on Windows

src/internals/scan.rs, tests/tests.rs
This can be used to get the messages generated by the console module.
=> feat: handle CALLBACK_MSG_CONSOLE_LOG callback type

src/internals/scan.rs
`x86_64` and `aarch64` `char`s are not both `i8`. x86 has signed characters, aarch has unsigned characters. To make this be cross-compatible we should be using `c_char` instead.  
This was broken in this commit: https://github.com/Hugal31/yara-rust/commit/6cdad5245a0e1d32b30d4c1cc4c0812bd9c7d6b9
=> use *const c_char instead of *const i8 to compile on aarch64

.github/workflows/tests.yml, src/internals/mod.rs, src/internals/module_import.rs, src/internals/scan.rs, yara-sys/bindings/yara-4.5.0-x86_64-apple-darwin.rs, yara-sys/bindings/yara-4.5.0-x86_64-pc-windows-gnu.rs, yara-sys/bindings/yara-4.5.0-x86_64-pc-windows-msvc.rs, yara-sys/bindings/yara-4.5.0-x86_64-unknown-linux-gnu.rs, yara-sys/bindings/yara-4.5.0-x86_64-unknown-linux-musl.rs, yara-sys/build.rs
Some modules in YARA need to be fed data to be usable, notably the cuckoo module. This works by setting the module data in the "import module" callback, as can be seen here:
<https://github.com/VirusTotal/yara/blob/923368eab/cli/yara.c#L1200>
This MR adds bindings to be able to do exactly this: the object related to this callback msg is wrapped in a YrModuleImport object, which exposes two functions:
- one to retrieve the module name
- one to set the module data
This makes the code looks like this:
```rust
let report = r#"{ "network": ... }"#;
let res = yara_scanner.scan_mem_callback(b"", |msg| {
if let yara::CallbackMsg::ImportModule(mut module) = msg {
if module.name() == Some(b"cuckoo") {
// Safety: report is alive for longer than the scan.
unsafe {
module.set_module_data( …
```
=> feat: add ability to set module data in scan callback

src/lib.rs, src/rules.rs
The `RulesetRule` type can be obtained from `Rules::get_rules`, but it wasn't publicly exported by the crate, making it impossible for an end user to e.g. implement a trait on it, or see what fields it contains in the docs without viewing the crate's source.
Additionally, the intra-doc links in the rustdoc for `Rules::unsafe_try_from` have been fixed.
=> Make RulesetRule public, fix intra-doc links

src/internals/iterator.rs, src/internals/matches.rs, src/internals/scan.rs, src/matches.rs, src/rules.rs, src/scanner.rs, tests/tests.rs
Yara exposes a few data in the details of a string match, notably which xor_key was used for the match. This MR simply exposes it in the rust object
=> feat: expose xor_key value in string instance matches
